import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import DashboardLayout from "@/components/layout";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KNN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen p-12">
        <Providers>
          <DashboardLayout  >
            {children}
          </DashboardLayout>
        </Providers></body>
    </html >
  );
}
